# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=100)),
                ('hanzi_traditional', models.CharField(max_length=100)),
                ('translation', models.TextField()),
                ('pinyin', models.CharField(max_length=4)),
                ('pinyin_number_notation', models.CharField(max_length=5)),
                ('stroke_count', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radicals', models.ManyToManyField(related_name='_hanzi_radicals_+', to='hanzi.Hanzi')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('hanzis', models.ManyToManyField(to='hanzi.Hanzi')),
            ],
        ),
    ]
