# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanzi',
            name='hanzi_traditional',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
