# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0002_auto_20170607_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanziClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HanziTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hanzi',
            name='translation',
        ),
        migrations.AlterField(
            model_name='hanzi',
            name='radicals',
            field=models.ManyToManyField(related_name='_hanzi_radicals_+', to='hanzi.Hanzi'),
        ),
        migrations.AddField(
            model_name='hanzi',
            name='translations',
            field=models.ManyToManyField(to='hanzi.HanziTranslation'),
        ),
    ]
