# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0003_auto_20170608_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanzi',
            name='classifiers',
            field=models.ManyToManyField(to='hanzi.HanziClassifier'),
        ),
    ]
