# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0004_hanzi_classifiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hanzitranslation',
            old_name='translations',
            new_name='translation',
        ),
    ]
