# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0005_auto_20170608_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinyin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin', models.CharField(max_length=4)),
                ('pinyin_number_notation', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='HanziClassifier',
            new_name='Classifier',
        ),
        migrations.RenameModel(
            old_name='HanziTranslation',
            new_name='Translation',
        ),
        migrations.RenameField(
            model_name='hanzi',
            old_name='hanzi_traditional',
            new_name='traditional',
        ),
        migrations.RemoveField(
            model_name='hanzi',
            name='pinyin',
        ),
        migrations.RemoveField(
            model_name='hanzi',
            name='pinyin_number_notation',
        ),
        migrations.AddField(
            model_name='hanzi',
            name='pinyins',
            field=models.ManyToManyField(to='hanzi.Pinyin'),
        ),
    ]
